---
abstract: 'Make your attributes chainable.'
author:
  - 'Aran Deltac <bluefeet@gmail.com>'
build_requires:
  Test::Simple: '0.94'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.015, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MooX-ChainedAttributes
requires:
  Moo: '1.004005'
  strictures: '1.004004'
resources:
  bugtracker: https://github.com/bluefeet/MooX-ChainedAttributes/issues
  homepage: https://github.com/bluefeet/MooX-ChainedAttributes
  repository: https://github.com/bluefeet/MooX-ChainedAttributes.git
version: '0.02'
